# PayFast subscription billing platform - developer Makefile.
#
# Cross-platform: tested on Windows Git Bash, macOS, and Linux.
# Make's default behavior (stop on first error) is equivalent to `set -e`
# for single-line recipes. Multi-line bash logic uses explicit `set -e`.

SHELL := /usr/bin/env bash
.SHELLFLAGS := -eu -o pipefail -c
.DEFAULT_GOAL := help

COMPOSE := docker compose -f infra/docker-compose.yml

.PHONY: help dev db-up db-down db-reset db-logs migrate migrate-new seed \
        backend frontend test lint clean ngrok

help: ## List available targets
	@echo ""
	@echo "PayFast platform - make targets"
	@echo "-------------------------------"
	@echo "  make help         List available targets"
	@echo "  make dev          Start infra, then print instructions for backend + frontend"
	@echo "  make db-up        Start Postgres, MailHog, Adminer (detached)"
	@echo "  make db-down      Stop infra containers"
	@echo "  make db-reset     DESTRUCTIVE: wipe pg volume and recreate (requires CONFIRM=1)"
	@echo "  make db-logs      Tail Postgres logs"
	@echo "  make migrate      Apply Alembic migrations to head"
	@echo "  make migrate-new  Create a new autogenerated migration (requires MSG=\"message\")"
	@echo "  make seed         Run backend/scripts/seed.py"
	@echo "  make backend      Run FastAPI dev server on :8000"
	@echo "  make frontend     Run Next.js dev server on :3000"
	@echo "  make test         Run backend + frontend tests"
	@echo "  make lint         Run backend ruff + frontend lint"
	@echo "  make clean        Remove caches and build artifacts (prompts first)"
	@echo "  make ngrok        Print ngrok / IPN setup instructions"
	@echo ""

dev: db-up ## Start infra and print next steps for backend + frontend
	@echo ""
	@echo "Infrastructure is up. Open two more terminals and run:"
	@echo ""
	@echo "    Terminal 2:   make backend"
	@echo "    Terminal 3:   make frontend"
	@echo ""
	@echo "Then open http://localhost:3000"
	@echo ""

db-up: ## Start Postgres + MailHog + Adminer (detached)
	$(COMPOSE) up -d
	@echo ""
	@echo "Services:"
	@echo "  Postgres  -> postgresql://postgres:postgres@localhost:5432/payfast"
	@echo "  MailHog   -> SMTP localhost:1025  |  UI http://localhost:8025"
	@echo "  Adminer   -> http://localhost:8080  (server: postgres)"
	@echo ""

db-down: ## Stop infra containers (preserves volume)
	$(COMPOSE) down

db-reset: ## DESTRUCTIVE: remove pg volume and recreate. Requires CONFIRM=1
	@if [ "$(CONFIRM)" != "1" ]; then \
	  echo "Refusing to reset: this removes the pg_data volume and all local data."; \
	  echo "Re-run with:  make db-reset CONFIRM=1"; \
	  exit 1; \
	fi
	$(COMPOSE) down -v
	$(COMPOSE) up -d
	@echo ""
	@echo "Database reset. Run 'make migrate && make seed' to repopulate."
	@echo ""

db-logs: ## Tail Postgres container logs
	$(COMPOSE) logs -f postgres

migrate: ## Apply Alembic migrations to head
	cd backend && uv run alembic upgrade head

migrate-new: ## Create a new autogenerated migration. Usage: make migrate-new MSG="add users table"
	@if [ -z "$(MSG)" ]; then \
	  echo "MSG is required. Usage:  make migrate-new MSG=\"describe the change\""; \
	  exit 1; \
	fi
	cd backend && uv run alembic revision --autogenerate -m "$(MSG)"

seed: ## Run the seed script
	cd backend && uv run python scripts/seed.py

backend: ## Run FastAPI dev server on :8000
	cd backend && uv run uvicorn app.main:app --reload --port 8000

frontend: ## Run Next.js dev server on :3000
	cd frontend && pnpm dev

test: ## Run backend + frontend tests
	@echo "--- backend tests ---"
	cd backend && uv run pytest
	@echo "--- frontend tests ---"
	cd frontend && pnpm test

lint: ## Run backend ruff + frontend lint
	@echo "--- backend lint (ruff) ---"
	cd backend && uv run ruff check .
	@echo "--- frontend lint ---"
	cd frontend && pnpm lint

clean: ## Remove caches and build artifacts (prompts first)
	@echo "This will remove:"
	@echo "  - backend: __pycache__, .pytest_cache, .mypy_cache, .ruff_cache"
	@echo "  - frontend: .next, .turbo, node_modules"
	@read -r -p "Continue? [y/N] " ans; \
	if [ "$$ans" != "y" ] && [ "$$ans" != "Y" ]; then \
	  echo "Aborted."; exit 0; \
	fi; \
	find backend -type d \( -name __pycache__ -o -name .pytest_cache -o -name .mypy_cache -o -name .ruff_cache \) -prune -exec rm -rf {} + 2>/dev/null || true; \
	rm -rf frontend/.next frontend/.turbo frontend/node_modules 2>/dev/null || true; \
	echo "Clean complete."

ngrok: ## Print ngrok + PayFast IPN setup instructions
	@echo ""
	@echo "PayFast IPN local testing via ngrok"
	@echo "-----------------------------------"
	@echo "1. Install ngrok:           https://ngrok.com/download"
	@echo "2. Authenticate:            ngrok config add-authtoken <YOUR_TOKEN>"
	@echo "3. Tunnel the backend:      ngrok http 8000"
	@echo "4. Copy the https URL ngrok prints, e.g. https://ab12-cd34.ngrok-free.app"
	@echo ""
	@echo "5. Update backend/.env:"
	@echo "     PAYFAST_RETURN_URL=<ngrok-url>/api/payfast/return"
	@echo "     PAYFAST_CANCEL_URL=<ngrok-url>/api/payfast/cancel"
	@echo ""
	@echo "6. Provide the IPN endpoint to PayFast:"
	@echo "     <ngrok-url>/api/payfast/ipn"
	@echo ""
	@echo "7. Restart the backend (make backend) so the new env is picked up."
	@echo ""
